version: "3.8"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.DockerFile
        ports:
            - 8098:80
        links:
            - app
        volumes:
            - ./:/var/www/yarlykov
        networks:
            - yarlykov_network
    app:
        build:
            context: .
            dockerfile: docker/fpm.DockerFile
        volumes:
            - ./:/var/www/yarlykov
        links:
            - mysql
        networks:
            - yarlykov_network
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - yarlykov_network
    npm:
        image: node:latest
        command: npm start
        volumes:
            - ./:/var/www/yarlykov
        working_dir: /var/www/yarlykov
        entrypoint: [ 'npm' ]
        networks:
            - yarlykov_network
    redis:
        image: redis:4.0
        ports:
            - "6382:6379"
        networks:
            - yarlykov_network
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DB_DATABASE}'
        volumes:
            - ./:/var/www/yarlykov
        ports:
            - "27017:27017"
        networks:
            - yarlykov_network
networks:
    yarlykov_network:
        driver: bridge
